# Generated by Django 5.1 on 2024-12-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
