# Generated by Django 5.1 on 2024-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_performance_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatrehall',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
